apiVersion: v1
kind: Service
metadata:
  name: UdacityFinalProject
  labels:
    app: UdacityFinalProject
spec:
  type: LoadBalancer
  selector:
    app: UdacityFinalProject
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP